### ISSUE TITLE
KeyError: 'playNavigationEndpoint' & More?

### ISSUE THREAD

**Issue by RustedBuckett** [sigma67/ytmusicapi#126]
Currently getting this error with some of my search's:
`
Traceback (most recent call last):
  File "f:/Spotify Python Application/run.py", line 113, in <module>
    getSong(song)
  File "f:/Spotify Python Application/run.py", line 18, in getSong
    data = ytmusic.search(song, filter='songs')
  File "C:\Users\Tom\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\ytmusicapi\mixins\browsing.py", line 119, in search
    search_results.extend(self.parser.parse_search_results(results, type))
  File "C:\Users\Tom\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\ytmusicapi\helpers.py", line 78, in _impl
    return method(self, *method_args, **method_kwargs)
  File "C:\Users\Tom\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\ytmusicapi\parsers\browsing.py", line 30, in parse_search_results
    search_result['videoId'] = nav(
KeyError: 'playNavigationEndpoint'
`

Using this code:
`   ytmusic = YTMusic()
   
   data = ytmusic.search(song, filter='songs')
   print(data)
   data = data[0]
   data = json.dumps(data)
   data = json.loads(data)`

My search query is this:
"Joel Fletcher - Swing - Joel Fletcher Remix"
However is not limited to this search query

Image: https://i.imgur.com/shoFsX5.png

I have tried removing the 'song' filter and this give me the results I'm looking for but then I have trouble with data['videoId']

Image: https://i.imgur.com/c1zsPwC.png
JSON Output: https://pastebin.com/YVHUgiwG

**Comment by sigma67** [comment]
Please check again with v0.12.1

**Comment by RustedBuckett** [comment]
LEGEND! FIxed
