### ISSUE TITLE
Error with custom Home Assistant integration

### ISSUE THREAD

**Issue by bobvmierlo** [sigma67/ytmusicapi#140]
See debug log output below:

```
Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:1181
Integration: YouTube Music Player (documentation, issues)
First occurred: 11:30:31 (1 occurrences)
Last logged: 11:30:31

Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 133, in check_api self._api = ytmusicapi.YTMusic(self._header_file) File "/usr/local/lib/python3.8/site-packages/ytmusicapi/ytmusic.py", line 96, in __init__ self.sapisid = sapisid_from_cookie(self.headers['Cookie']) File "/usr/local/lib/python3.8/site-packages/ytmusicapi/helpers.py", line 57, in sapisid_from_cookie return cookie['__Secure-3PAPISID'].value KeyError: '__Secure-3PAPISID'
```

**Comment by sigma67** [comment]
Please report at the repository of your project `ytube_music_player`. It seems like a cookie issue.
