### ISSUE TITLE
Secure-3PAPISID

### ISSUE THREAD

**Issue by leeiberry** [sigma67/ytmusicapi#145]
get the following error :  

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:1229
Integration: YouTube Music Player (documentation, issues)
First occurred: 1:26:20 PM (15 occurrences)
Last logged: 1:35:18 PM

Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 147, in check_api self._api = ytmusicapi.YTMusic(self._header_file) File "/usr/local/lib/python3.8/site-packages/ytmusicapi/ytmusic.py", line 96, in __init__ self.sapisid = sapisid_from_cookie(self.headers['Cookie']) File "/usr/local/lib/python3.8/site-packages/ytmusicapi/helpers.py", line 57, in sapisid_from_cookie return cookie['__Secure-3PAPISID'].value KeyError: '__Secure-3PAPISID'
Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 1042, in play_media self._tracks = self._api.get_playlist(playlistId=media_id)['tracks'] AttributeError: 'NoneType' object has no attribute 'get_playlist'
Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 1044, in play_media self._tracks = self._api.get_album(browseId=media_id)['tracks'] AttributeError: 'NoneType' object has no attribute 'get_album'

any ideas ?
have followed the install instructions without muck luck !

LeeB

**Comment by sigma67** [comment]
That means your cookie is incomplete and missing a required value.

**Comment by sigma67** [comment]
Likely better to open this issue at https://github.com/KoljaWindeler/ytube_music_player.
