### ISSUE TITLE
Continuations broken in get_library_upload_albums?

### ISSUE THREAD

**Issue by impliedchaos** [sigma67/ytmusicapi#158]
This was working yesterday, so I don't know if it's just specific to my google account.

```python
from ytmusicapi import YTMusic
y = YTMusic('auth.json')
a = y.get_library_upload_albums()
# Above works fine.
a = y.get_library_upload_albums(limit=100)
# But the continuations generates the following error:
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/ytmusicapi/ytmusicapi/mixins/uploads.py", line 89, in get_library_upload_albums
    parse_func))
  File "/home/pi/ytmusicapi/ytmusicapi/parsers/utils.py", line 107, in get_continuations
    response = request_func(additionalParams)
  File "/home/pi/ytmusicapi/ytmusicapi/mixins/uploads.py", line 85, in <lambda>
    endpoint, body, additionalParams)
  File "/home/pi/ytmusicapi/ytmusicapi/ytmusic.py", line 116, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 400: Bad Request.
Request contains an invalid argument.
```

Thanks!

**Comment by sigma67** [comment]
It is working perfectly fine for me. Has your user interface on the web changed for albums? Perhaps you're part of a beta test.

**Comment by impliedchaos** [comment]
And it's working perfectly again for me today.  I love Google. 🙄  Closing.
