### ISSUE TITLE
Failling while fetch artist albums

### ISSUE THREAD

**Issue by bohrasankalp** [sigma67/ytmusicapi#162]
Logs when I try to fetch artist _ albums/singles

```
Traceback (most recent call last):
  File "/home/sony/PycharmProjects/pythonProject/main.py", line 33, in <module>
    singles = ytmusic.get_artist_albums(channelId, singleParam)
  File "/home/sony/Desktop/yt/lib/python3.6/site-packages/ytmusicapi/mixins/browsing.py", line 260, in get_artist_albums
    results = nav(response, SINGLE_COLUMN_TAB + SECTION_LIST + MUSIC_SHELF)
  File "/home/sony/Desktop/yt/lib/python3.6/site-packages/ytmusicapi/parsers/utils.py", line 195, in nav
    raise err
  File "/home/sony/Desktop/yt/lib/python3.6/site-packages/ytmusicapi/parsers/utils.py", line 189, in nav
    root = root[k]
KeyError: 'musicShelfRenderer'

Process finished with exit code 1
```

**Comment by sigma67** [comment]
See #160, fixed yesterday

**Comment by bohrasankalp** [comment]
Reopening issue, sharing a code snippet


``` python
    channelId = 'UC8AQ6pEYVYy_gSD-XixbhPQ'
    artist = ytmusic.get_artist(channelId)
    albums = ytmusic.get_artist_albums(artist['albums']['browseId'], artist['albums']['params'])
```

**Comment by bohrasankalp** [comment]
@sigma67 Take a look

**Comment by sigma67** [comment]
Are you on latest master? As I said it was fixed yesterday. No new version has been published yet. Your channel works fine for me

`pip install git+https://github.com/sigma67/ytmusicapi`
