### ISSUE TITLE
get_playlist() fails if description is blank

### ISSUE THREAD

**Issue by beville** [sigma67/ytmusicapi#17]
If I call get_playlist() on a playlist without a description I get:

```
Traceback (most recent call last):
  File "./ytmusic.py", line 100, in <module>
    main()
  File "./ytmusic.py", line 71, in main
    clear_playlist(ytmusic, playlist_id)
  File "./ytmusic.py", line 43, in clear_playlist
    playlist = ytmusic.get_playlist(id, limit=100)
  File "/usr/local/lib/python3.8/dist-packages/ytmusicapi/ytmusic.py", line 721, in get_playlist
    playlist['description'] = header['description']['runs'][0]['text']
KeyError: 'description'
```
If I fill in a description via the web UI, the call works.  After I remove the value in the web UI, the call fails again.

**Comment by hematogender** [comment]
Thanks for the report! This should be resolved soon.
