### ISSUE TITLE
Problems playing album from automation

### ISSUE THREAD

**Issue by SifuDaigo** [sigma67/ytmusicapi#170]
Whenever I try to start an album via the `play_media`-service and feeding it the album-ID I get the following error:

```
Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 1080, in play_media self._tracks = self._api.get_album(browseId=media_id)['tracks'] File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/browsing.py", line 432, in get_album response = self._send_request(endpoint, body) File "/usr/local/lib/python3.8/site-packages/ytmusicapi/ytmusic.py", line 129, in _send_request raise Exception(message + error) Exception: Server returned HTTP 400: Bad Request. Unknown error.
Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 1078, in play_media self._tracks = self._api.get_playlist(playlistId=media_id)['tracks'] File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/playlists.py", line 67, in get_playlist results = nav(response, File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 210, in nav raise err File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 204, in nav root = root[k] KeyError: 'contents'
```

I tried both `media_content_type`-possibilities of `album` and `playlist`. Playing albums via the media-browser works fine!

**Comment by SifuDaigo** [comment]
Update: Got the wrong media_id - copied it from the URL on the Detail-Page of the album - not on https://music.youtube.com/library/albums. Sorry for the confusion!
