### ISSUE TITLE
exception occurs if a playlist with no titles exists in library when calling get_library_playlists

### ISSUE THREAD

**Issue by oetken** [sigma67/ytmusicapi#175]
# Description
If there is any playlist in your library that contains zero tracks the following exception is thrown:
```
>>> search_results = ytmusic.get_library_playlists(limit=99)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/z001131e/.local/lib/python3.9/site-packages/ytmusicapi/mixins/library.py", line 32, in get_library_playlists
    playlists = parse_content_list(results['items'][1:], parse_playlist)
  File "/home/z001131e/.local/lib/python3.9/site-packages/ytmusicapi/parsers/browsing.py", line 157, in parse_content_list
    contents.append(parse_func(result['musicTwoRowItemRenderer']))
  File "/home/z001131e/.local/lib/python3.9/site-packages/ytmusicapi/parsers/browsing.py", line 194, in parse_playlist
    'title': nav(data, TITLE_TEXT),
  File "/home/z001131e/.local/lib/python3.9/site-packages/ytmusicapi/parsers/utils.py", line 210, in nav
    raise err
  File "/home/z001131e/.local/lib/python3.9/site-packages/ytmusicapi/parsers/utils.py", line 204, in nav
    root = root[k]
```

**Comment by sigma67** [comment]
Can you screenshot the playlist in question that's causing the error? The error you posted does not seem related to the count
