### ISSUE TITLE
unfortunately we hit an error in the sub api

### ISSUE THREAD

**Issue by olskar** [sigma67/ytmusicapi#195]
`============= ytube_music_player Integration Error ================
2021-05-04 12:42:53 ERROR (MainThread) [custom_components.ytube_music_player.media_player] unfortunately we hit an error in the sub api, please open a ticket at
2021-05-04 12:42:53 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://github.com/sigma67/ytmusicapi/issues
2021-05-04 12:42:53 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:
2021-05-04 12:42:53 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
File "/config/custom_components/ytube_music_player/media_player.py", line 1136, in async_play_media
playlist_info = await self.hass.async_add_executor_job(self._api.get_playlist,media_id)
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/playlists.py", line 67, in get_playlist
results = nav(response,
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 147, in nav
raise err
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 141, in nav
root = root[k]
KeyError: 'contents'
2021-05-04 12:42:53 ERROR (MainThread) [custom_components.ytube_music_player.media_player]
thanks, Kolja
2021-05-04 12:42:53 ERROR (MainThread) [custom_components.ytube_music_player.media_player] ============= ytube_music_player Integration Error ================
2021-05-04 12:42:53 WARNING (SyncWorker_8) [pychromecast.controllers] STOP command requested but no session is active.`

**Comment by sigma67** [comment]
Please add the relevant playlistId of your call and enable debug mode. Also please post such issues to KoljaWindeler/ytube_music_player first unless you can say for sure it is an issue with ytmusicapi
