### ISSUE TITLE
Failed to play Music

### ISSUE THREAD

**Issue by DravenSA** [sigma67/ytmusicapi#197]
This error originated from a custom integration.

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:1157
Integration: YouTube Music Player (documentation, issues)
First occurred: 16:19:34 (1 occurrences)
Last logged: 16:19:34

- Failed to get own(!) URL for track, further details below. Will not try YouTube method

This error originated from a custom integration.

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:1158
Integration: YouTube Music Player (documentation, issues)
First occurred: 16:19:34 (1 occurrences)
Last logged: 16:19:34

Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 1135, in async_get_url if(streamingData[streamId].get('url') is None): KeyError: 0

Logger: homeassistant.components.cast.media_player
Source: components/cast/media_player.py:316
Integration: Google Cast (documentation, issues)
First occurred: 16:19:35 (1 occurrences)
Last logged: 16:19:35

Failed to cast media https://www.home-assistant.io/images/cast/splash.png. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address

Logger: homeassistant.util.async_
Source: util/async_.py:132
First occurred: 16:19:35 (1 occurrences)
Last logged: 16:19:35

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for ytube_music_player doing I/O at custom_components/ytube_music_player/media_player.py, line 1161: _LOGGER.error(self._api.get_song(videoId))

This error originated from a custom integration.

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:1518
Integration: YouTube Music Player (documentation, issues)
First occurred: 16:19:35 (1 occurrences)
Last logged: 16:19:35

Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 1135, in async_get_url if(streamingData[streamId].get('url') is None): KeyError: 0 During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 1161, in async_get_url _LOGGER.error(self._api.get_song(videoId)) File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/browsing.py", line 591, in get_song response = requests.get(endpoint, params, headers=self.headers, proxies=self.proxies) File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 76, in get return request('get', url, params=params, **kwargs) File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request return session.request(method=method, url=url, **kwargs) File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send resp = conn.urlopen( File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen httplib_response = self._make_request( File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request conn.request(method, url, **httplib_request_kw) File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request super(HTTPConnection, self).request(method, url, body=body, headers=headers) File "/usr/local/lib/python3.8/http/client.py", line 1252, in request self._send_request(method, url, body, headers, encode_chunked) File "/usr/local/lib/python3.8/http/client.py", line 1263, in _send_request self.putrequest(method, url, **skips) File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 214, in putrequest return _HTTPConnection.putrequest(self, method, url, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 151, in protected_loop_func check_loop() File "/usr/src/homeassistant/homeassistant/util/async_.py", line 140, in check_loop raise RuntimeError( RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/ytube_music_player/media_player.py, line 1161: _LOGGER.error(self._api.get_song(videoId))

Logger: homeassistant.components.automation.youtubemusic_2
Source: helpers/script.py:1337
Integration: Automation (documentation, issues)
First occurred: 16:19:35 (1 occurrences)
Last logged: 16:19:35

YouTubeMusic: Error executing script. Invalid data for call_service at pos 4: string value is None for dictionary value @ data['media_content_id']

Logger: homeassistant.components.automation.youtubemusic_2
Source: components/automation/__init__.py:508
Integration: Automation (documentation, issues)
First occurred: 16:19:35 (1 occurrences)
Last logged: 16:19:35

Error while executing automation automation.youtubemusic_2: string value is None for dictionary value @ data['media_content_id']

**Comment by KoljaWindeler** [comment]
we're already working on it here https://github.com/KoljaWindeler/ytube_music_player/issues/97, please close this issue here
