### ISSUE TITLE
Please clarify the setup documentation

### ISSUE THREAD

**Issue by salsaman** [sigma67/ytmusicapi#228]
Hi, I have been struggling to get  thius set up,, and am not finding the setup instructions very helpful.
Please can you clarify what the general forrmat of the request headers text and the 'cookie' should look like.. I have gone through the steps best as I can make out, but when I try to use the cookie (?)  in Home Assistant, I keep getting an error teeling me it is unable to connect.. Without clearer exemples to follow, I cannot be sure if the issue is with Home Assistant integration or with the text which I am pasting in the Cookie field.

**Comment by sigma67** [comment]
Hi, please refer to the documentation to point out where exactly it is unclear:  https://ytmusicapi.readthedocs.io/en/latest/setup.html

For Home Assistant, please refer to https://github.com/KoljaWindeler/ytube_music_player/

**Comment by salsaman** [comment]
The problem I am having is this - when I try to do the setup in Home Assistant, there is a text field where I am supposed to enter the cookie text. I followed the instructions and open dev tools, searehd for /browse and found the request headers. Amongst the headers there is a "Cookie" field. I copied the value into the HA setup and it came back with an error "Something with your cookie wasn't right. Format and fields are ok but the login failed:. So then reading the documentation, I see "Using the headers in your project". Thus I figured maybe I had to follow the instructions and input the headers, and paste in the resulting output. I treid this, and again received the same error in HA.. So then I began to question exactly what I was supposed to cut and paste..
Since there was no example of what the cookie data is supposed to look like, I cannot tell if I am pasting in the necessary data or not. The cookie data I have begins with "VISITOR_INFO1_LIVE=...: and then contains several other pieces of data separated with ";" ending with "__Secure-3PSIDCC=".. It is not clear if should paste in all of this, or if in fact I need to run the python console commands and paste in the resulting output. Anyway, neither worked for me, I continued to get the same error. Since there are no examples of what the cookie data is supposed to look like, I have no way of telling if the problem is with the data returned in the browser, or if the problem is with the HA setup. Including an example of what the cookie data should look like would be useful in try to troubleshoot this issue.

**Comment by salsaman** [comment]
Checking logs in Homea Assistent I see the following:

2021-09-26 15:34:59 ERROR (MainThread) [custom_components.ytube_music_player.config_flow] Traceback (most recent call last):
File "/config/custom_components/ytube_music_player/config_flow.py", line 188, in async_check_data
YTMusic.setup(filepath = user_input[CONF_HEADER_PATH], headers_raw = c)
File "/usr/local/lib/python3.9/site-packages/ytmusicapi/ytmusic.py", line 156, in setup
return setup(filepath, headers_raw)
File "/usr/local/lib/python3.9/site-packages/ytmusicapi/setup.py", line 36, in setup
raise Exception(
Exception: The following entries are missing in your headers: cookie, x-goog-authuser. Please try a different request (such as /browse) and make sure you are logged in.

However, that field does exist in the cookie text, ie:
"x-goog-authuser": "0",

**Comment by sigma67** [comment]
If you want me to check your cookie you can send it to ytmusicapi@gmail.com, maybe I can find the issue
