### ISSUE TITLE
YTMusic.get_library_playlists() -> Server returned HTTP 500

### ISSUE THREAD

**Issue by willcharlton** [sigma67/ytmusicapi#273]
Issue listing playlists in user library.

## Code / Response

```python
$ python
Python 3.8.9 (default, Mar 30 2022, 13:51:17) 
[Clang 13.1.6 (clang-1316.0.21.2.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ytmusicapi import YTMusic
>>> yt = YTMusic('./headers_auth.json')
>>> yt.get_library_playlists()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/me/test/ytmusicapi/.venv/lib/python3.8/site-packages/ytmusicapi/mixins/library.py", line 27, in get_library_playlists
    response = self._send_request(endpoint, body)
  File "/Users/me/test/ytmusicapi/.venv/lib/python3.8/site-packages/ytmusicapi/ytmusic.py", line 144, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 500: Internal Server Error.
Internal error encountered.
>>> 
```
I have verified that I can retrieve Public playlists in my account, but not private ones. I'm not sure if that's related, but seemed relevant.

**Comment by sigma67** [comment]
Seems like an issue with your headers. Can you call other private endpoints?
