### ISSUE TITLE
500 Internal Server Error when searching

### ISSUE THREAD

**Issue by alanhamlett** [sigma67/ytmusicapi#363]
Response:
```
{
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "errors": [
      {
        "message": "Internal error encountered.",
        "domain": "global",
        "reason": "backendError"
      }
    ],
    "status": "INTERNAL"
  }
}
```

Example code:

```python
from ytmusicapi import YTMusic
yt = YTMusic(headers, user_id)
query = "OM Unit Lightworkers Call Feat. Kromestar"
yt.search(query)
```

Traceback:
```
Traceback (most recent call last):
  File "spotifyplaylist_to_ytmusic/YouTube.py", line 160, in main
    videoIds = ytmusic.search_songs(playlist['tracks'])
  File "spotifyplaylist_to_ytmusic/YouTube.py", line 74, in search_songs
    result = self.api.search(query)
  File "spotifyplaylist_to_ytmusic/venv/lib/python3.9/site-packages/ytmusicapi/mixins/search.py", line 151, in search
    response = self._send_request(endpoint, body)
  File "spotifyplaylist_to_ytmusic/venv/lib/python3.9/site-packages/ytmusicapi/ytmusic.py", line 146, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 500: Internal Server Error.
```

**Comment by sigma67** [comment]
As you can see it's a backend error, so there's not much this project (client) can do about it.

**Comment by alanhamlett** [comment]
The backend error seems persistent, does it work for you? If not, what's the point of having that search method if it always fails?

**Comment by sigma67** [comment]
I cannot reproduce this, so it's probably something specific to your account or a rollout in progress. `search` works fine for my account.

**Comment by alanhamlett** [comment]
Yes, I think you're right. Thanks!
