### ISSUE TITLE
search: `list index out of range` for some search terms

### ISSUE THREAD

**Issue by ageisen2000** [sigma67/ytmusicapi#429]
Here is the dump
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\adamg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts\spotify_to_ytmusic.exe\__main__.py", line 7, in <module>
  File "C:\Users\adamg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\spotify_to_ytmusic\main.py", line 86, in main
    args.func(args)
  File "C:\Users\adamg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\spotify_to_ytmusic\controllers.py", line 79, in liked
    _create_ytmusic(args, playlist, ytmusic)
  File "C:\Users\adamg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\spotify_to_ytmusic\controllers.py", line 60, in _create_ytmusic
    videoIds = ytmusic.search_songs(playlist["tracks"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adamg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\spotify_to_ytmusic\ytmusic.py", line 32, in search_songs
    result = self.api.search(query)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adamg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ytmusicapi\mixins\search.py", line 218, in search
    parse_search_results(results, search_result_types, type, category))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adamg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ytmusicapi\parsers\search.py", line 142, in parse_search_results
    return [
           ^
  File "C:\Users\adamg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ytmusicapi\parsers\search.py", line 143, in <listcomp>
    parse_search_result(result[MRLIR], search_result_types, resultType, category)
  File "C:\Users\adamg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ytmusicapi\parsers\search.py", line 80, in parse_search_result
    search_result['name'] = get_item_text(data, 1, 2)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adamg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ytmusicapi\parsers\_utils.py", line 30, in get_item_text
    return column['text']['runs'][run_index]['text']
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
IndexError: list index out of range
```

**Comment by sigma67** [comment]
So I'm trying with some pretty large playlists right now but failing to reproduce. It might be something specific to your accounts or a very rare bug where the name is missing on a profile result.

It would be very helpful if you could add the following debugging code to your local ytmusicapi installation and paste the output data here whenever you see the issue. Instead of this line

https://github.com/sigma67/ytmusicapi/blob/6660058a47dc31cefe1c3686067aeef0333c2590/ytmusicapi/parsers/search.py#L80

add

```python
        search_result['name'] = get_item_text(data, 1, 2, True)
        if search_result['name'] == None:
            print(data)
            sys.exit()  # optional to stop when you find the issue
```

**Comment by sigma67** [comment]
Managed to reproduce. I figure it's safe to ignore the value if absent since there are no other flexitems on this type of search result (yet).

**Comment by kler** [comment]
Great, thx!

I also made a run with the changes you proposed, and this is the result:

``` python
{
    'trackingParams': 'CBQQyfQCGAAiEwiMtueJ2PiAAxXnzU8IHYFND-E=',
    'thumbnail': {
        'musicThumbnailRenderer': {
            'thumbnail': {},
            'thumbnailCrop': 'MUSIC_THUMBNAIL_CROP_CIRCLE',
            'thumbnailScale': 'MUSIC_THUMBNAIL_SCALE_ASPECT_FILL',
            'trackingParams': 'CBUQhL8CIhMIjLbnidj4gAMV581PCB2BTQ_h'}
    },
    'flexColumns': [
        {
            'musicResponsiveListItemFlexColumnRenderer': {
                'text': {'runs': [{'text': 'Radio FM 432hz'}]},
                'displayPriority': 'MUSIC_RESPONSIVE_LIST_ITEM_COLUMN_DISPLAY_PRIORITY_HIGH'}
        },
        {
            'musicResponsiveListItemFlexColumnRenderer': {
                'text': {
                    'runs': [
                        {'text': 'Profile'}
                    ]
                },
                'displayPriority': 'MUSIC_RESPONSIVE_LIST_ITEM_COLUMN_DISPLAY_PRIORITY_HIGH'
            }
        }
        ],
        'flexColumnDisplayStyle': 'MUSIC_RESPONSIVE_LIST_ITEM_FLEX_COLUMN_DISPLAY_STYLE_TWO_LINE_STACK',
        'navigationEndpoint': {
            'clickTrackingParams': 'CBQQyfQCGAAiEwiMtueJ2PiAAxXnzU8IHYFND-E=',
            'browseEndpoint': {
                'browseId': 'UCf95fGmczd-0lzsCviETqKA',
                'browseEndpointContextSupportedConfigs': {
                    'browseEndpointContextMusicConfig': {
                        'pageType': 'MUSIC_PAGE_TYPE_UNKNOWN'
                    }
                }
            }
        },
        'itemHeight': 'MUSIC_RESPONSIVE_LIST_ITEM_HEIGHT_TALL'
}
```

There is unfortunately also a second problem in the `nav()` function in `navigation.py` - but didn't store the stack trace from when I had the error. Will possibly come back with that in another bug report if I hit it again.
