### ISSUE TITLE
KeyError: 'gridRenderer' for `get_artist_albums`

### ISSUE THREAD

**Issue by fabi321** [sigma67/ytmusicapi#439]
Whenever using `YTMusic.get_artist_albums`, it fails with a `KeyError: 'gridRenderer'`

**To Reproduce**
```
>>> from ytmusicapi import YTMusic
>>> ytmusic = YTMusic()
>>> ytmusic.get_artist_albums('UCM-CWGUijAC-8idv6k6Fygw', 'ggMIegYIARoCAQI%3D')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/project/.venv/lib/python3.11/site-packages/ytmusicapi/mixins/browsing.py", line 255, in get_artist_albums
    results = nav(response, SINGLE_COLUMN_TAB + SECTION_LIST_ITEM + GRID_ITEMS)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/project/.venv/lib/python3.11/site-packages/ytmusicapi/navigation.py", line 81, in nav
    raise err
  File "~/project/.venv/lib/python3.11/site-packages/ytmusicapi/navigation.py", line 75, in nav
    root = root[k]
           ~~~~^^^
KeyError: 'gridRenderer'
```

**Comment by sigma67** [comment]
Seems there's been an update and you can now filter by Albums/Singles and sort.

PR welcome.

**Comment by fabi321** [comment]
I was to blame for that last mistake. I wrongly assumed, that I could use the channel id as browseId for getting albums, while that isn't always the case. Fixing that fixed the issue.

**Comment by sigma67** [comment]
#441 for the new features

**Comment by sigma67** [comment]
#441 is now completed
