### ISSUE TITLE
get_artist_albums method producing KeyError: 'musicCarouselShelfRenderer'

### ISSUE THREAD

**Issue by Utkarsh-vishnoi** [sigma67/ytmusicapi#489]
On executing `get_artist_albums`, It gives me `KeyError: 'musicCarouselShelfRenderer'`. I have double checked and make sure, I am using the latest version i.e. version 1.3.2. I have provided the code to reproduce the error below.

**To Reproduce**
Run the below piece of code
```
#!/usr/bin/env python3

from ytmusicapi import YTMusic

if __name__ == '__main__':
    ytmusic = YTMusic("oauth.json")
    artistParam = ytmusic.get_artist(channelId='UCedvOgsKFzcK3hA5taf3KoQ')['albums']['params'] // Channel: Eminem
    result = ytmusic.get_artist_albums(channelId='UCedvOgsKFzcK3hA5taf3KoQ', params=artistParam)
    print(result)
```

**Additional context**
I have used oauth for authentication
I get the following error upon executing the code.
```
Traceback (most recent call last):
  File "/workspaces/muse/DB/test.py", line 8, in <module>
    result = ytmusic.get_artist_albums(channelId='UCedvOgsKFzcK3hA5taf3KoQ', params=artistParam)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/ytmusicapi/mixins/browsing.py", line 256, in get_artist_albums
    results = nav(results, GRID_ITEMS, True) or nav(results, CAROUSEL_CONTENTS)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/ytmusicapi/navigation.py", line 82, in nav
    raise err
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/ytmusicapi/navigation.py", line 76, in nav
    root = root[k]
KeyError: 'musicCarouselShelfRenderer'
```

**Comment by Utkarsh-vishnoi** [comment]
Hi,
Anymore information needed from my end?

Thanks & Regards,
Utkarsh Vishnoi

**Comment by sigma67** [comment]
```python
from ytmusicapi import YTMusic
ytmusic = YTMusic()
artistParam = ytmusic.get_artist(channelId='UCedvOgsKFzcK3hA5taf3KoQ')
result = ytmusic.get_artist_albums(channelId=artistParam['albums']['browseId'], params=artistParam['albums']['params'])
```
