### ISSUE TITLE
KeyError: 'singleColumnBrowseResultsRenderer'

### ISSUE THREAD

**Issue by cyperdark** [sigma67/ytmusicapi#616]
**Describe the bug**
Got this error when trying to get results from ``get_playlist``
<br>

**To Reproduce**
1. Auth via this https://ytmusicapi.readthedocs.io/en/stable/setup/browser.html#manual-file-creation
2. create file `.auth.json`
3. run `python file.py`
<br>

**Code**
```
from ytmusicapi import YTMusic

MUSIC = YTMusic(".auth.json", language='en')


playlists = MUSIC.get_library_playlists()
print("ID", playlists[0]['playlistId'])

items = MUSIC.get_playlist(playlists[0]['playlistId'], 100)
print(items)
```
<br>

**Additional context**
```
 python index.py
ID LM
Traceback (most recent call last):
  File "F:\coding\wip\yt-music-manager\index.py", line 10, in <module>
    items = MUSIC.get_playlist(playlists[0]['playlistId'], 100)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\ytmusicapi\mixins\playlists.py", line 110, in get_playlist
    results = nav(response,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\ytmusicapi\navigation.py", line 81, in nav
    raise err
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\ytmusicapi\navigation.py", line 75, in nav
    root = root[k]
KeyError: 'singleColumnBrowseResultsRenderer'
```

**Comment by sigma67** [comment]
What version of ytmusicapi are you using?

**Comment by cyperdark** [comment]
ytmusicapi==0.25.2

**Comment by cyperdark** [comment]
oh, i was using very old version, and i thought `pip install ytmusicapi` would update it but i was wrong

forced to update and now it's fine
