### ISSUE TITLE
Error when querying get_home()

### ISSUE THREAD

**Issue by Batwam** [sigma67/ytmusicapi#668]
**get_home() query no longer works**
Hello, I noticed recently that the script I used to get music suggestions no longer works. The error message isn't very clear so I'm not sure what the issue might be but the script worked a few days ago and also returns results when using something like `yt.search("Oasis Wonderwall")`...

**To Reproduce**

**Test Script  using get_home ( doesn't work)**
```py
from ytmusicapi import YTMusic
import pprint

yt = YTMusic(oauth.json")
search_results = yt.get_home(30)
pprint.pprint(search_results)
```
**Result**
```sh
Traceback (most recent call last):
  File "/home/user/.local/share/pipx/venvs/ytmusicapi/lib/python3.12/site-packages/ytmusicapi/navigation.py", line 107, in nav
    root = root[k]
           ~~~~^^^
KeyError: 'watchEndpoint'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/ytmusicapi_home.py", line 14, in <module>
    search_results = yt.get_home(30)
                     ^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/ytmusicapi/lib/python3.12/site-packages/ytmusicapi/mixins/browsing.py", line 118, in get_home
    home.extend(parse_mixed_content(results))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/ytmusicapi/lib/python3.12/site-packages/ytmusicapi/parsers/browsing.py", line 27, in parse_mixed_content
    content = parse_song(data)
              ^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/ytmusicapi/lib/python3.12/site-packages/ytmusicapi/parsers/browsing.py", line 86, in parse_song
    "videoId": nav(result, NAVIGATION_VIDEO_ID),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/ytmusicapi/lib/python3.12/site-packages/ytmusicapi/navigation.py", line 111, in nav
    raise type(e)(f"Unable to find '{k}' using path {items!r} on {root!r}, exception: {e}")
KeyError: "Unable to find 'watchEndpoint' using path ['navigationEndpoint', 'watchEndpoint', 'videoId'] on {'clickTrackingParams': 'CLECEKCzAhgAIhMIiZiNtpq6iQMVTgq3AB2ZTTys', 'browseEndpoint': {'browseEndpointContextSupportedConfigs': {'browseEndpointContextMusicConfig': {'pageType': 'MUSIC_PAGE_TYPE_ARTIST'}}}}, exception: 'watchEndpoint'"

```

Note that I just tried to generate oauth using another account and this appears to work. Also, I just modified navigation.py to print the content of the `root` variable and it does contain data, it even contains keys called `watchEndpoint` so I'm not 100% sure what the case of the issue is... could it be the some issue with the type of playlists (music Vs videos?)

Edit2: I tried using get_home(1) and it worked, then tried again and it no longer work. So perhaps an again issue with the content of the results?

Edit3: using timestamps, I was able to establish that the script does run for a few entries. However, when it lands on some it cannot find the `'watchEndpoint'` key and crashing instead of skipping to the next. Is it possible to continue rather than crashing?

**Comment by Batwam** [comment]
ok, I think that I "solved it" by updating navigation.py from
```py
    try:
        for k in items:
            root = root[k]
    except (KeyError, IndexError, TypeError) as e:
        if none_if_absent:
            return None
        raise type(e)(f"Unable to find '{k}' using path {items!r} on {root!r}, exception: {e}")
    return root
```

to
```py
    try:
        for k in items:
            root = root[k]
    except (KeyError, IndexError, TypeError) as e:
        if none_if_absent:
            return None
            raise type(e)(f"Unable to find '{k}' using path {items!r} on {root!r}, exception: {e}")
    return root
```

**Comment by sigma67** [comment]
Hi @Batwam

`get_home` is hard to debug because it is very user dependent. Could you provide reproduction instructions?

What did your homepage look like?

**Comment by Batwam** [comment]
Hello, apologies for the delay, responding here even through you closed it as I still believe that this is a bug. I tried to progressively increase the get_home(x) value to see at which section if would fail. 

Turns out to be related to the "Listen Again" category with albums which I believe are manual uploads. Some have a link which is 'https://music.youtube.com/channel/undefined'.

![Screenshot From 2024-12-27 13-38-39](https://github.com/user-attachments/assets/c480236f-6507-48eb-b984-2cefa996aba9)

log below where I'm printing `root[k]`:
```
- Listen again
----------------
- {'thumbnailRenderer': {'musicThumbnailRenderer': {'thumbnail': {'thumbnails': [{'url': 'https://lh3.googleusercontent.com/a-/ALV-UjUbQGzZ2_DL08yAi4pQAupcyj2upWfEkLSFajn7LbQ8dDngP9y4cQ=w226-h226-l90-rj', 'width': 226, 'height': 226}, {'url': 'https://lh3.googleusercontent.com/a-/ALV-UjUbQGzZ2_DL08yAi4pQAupcyj2upWfEkLSFajn7LbQ8dDngP9y4cQ=w544-h544-l90-rj', 'width': 544, 'height': 544}]}, 'thumbnailCrop': 'MUSIC_THUMBNAIL_CROP_CIRCLE', 'thumbnailScale': 'MUSIC_THUMBNAIL_SCALE_ASPECT_FILL', 'trackingParams': 'CIIBEIS_AiITCO2ZjOChx4oDFVqO2AUdD3cBXg=='}}, 'aspectRatio': 'MUSIC_TWO_ROW_ITEM_THUMBNAIL_ASPECT_RATIO_SQUARE', 'title': {'runs': [{'text': 'Preston Reed', 'navigationEndpoint': {'clickTrackingParams': 'CHwQoLMCGAAiEwjtmYzgoceKAxVajtgFHQ93AV4=', 'browseEndpoint': {'browseId': 'UCvk7l9iOh4N_TwF0KFOmbQw', 'browseEndpointContextSupportedConfigs': {'browseEndpointContextMusicConfig': {'pageType': 'MUSIC_PAGE_TYPE_ARTIST'}}}}}]}, 'subtitle': {'runs': [{'text': '11.4K subscribers'}]}, 'navigationEndpoint': {'clickTrackingParams': 'CHwQoLMCGAAiEwjtmYzgoceKAxVajtgFHQ93AV4=', 'browseEndpoint': {'browseId': 'UCvk7l9iOh4N_TwF0KFOmbQw', 'browseEndpointContextSupportedConfigs': {'browseEndpointContextMusicConfig': {'pageType': 'MUSIC_PAGE_TYPE_ARTIST'}}}}, 'trackingParams': 'CHwQoLMCGAAiEwjtmYzgoceKAxVajtgFHQ93AV4=', 'menu': {'menuRenderer': {'items': [{'menuNavigationItemRenderer': {'text': {'runs': [{'text': 'Shuffle play'}]}, 'icon': {'iconType': 'MUSIC_SHUFFLE'}, 'navigationEndpoint': {'clickTrackingParams': 'CIEBEJrzBRgAIhMI7ZmM4KHHigMVWo7YBR0PdwFe', 'watchPlaylistEndpoint': {'playlistId': 'RDAO8B2oAM_ijCcc991Z5qQCdA', 'params': 'wAEB8gECGAE%3D'}}, 'trackingParams': 'CIEBEJrzBRgAIhMI7ZmM4KHHigMVWo7YBR0PdwFe'}}, {'menuNavigationItemRenderer': {'text': {'runs': [{'text': 'Start radio'}]}, 'icon': {'iconType': 'MIX'}, 'navigationEndpoint': {'clickTrackingParams': 'CIABEJvzBRgBIhMI7ZmM4KHHigMVWo7YBR0PdwFe', 'watchPlaylistEndpoint': {'playlistId': 'RDEM8B2oAM_ijCcc991Z5qQCdA', 'params': 'wAEB'}}, 'trackingParams': 'CIABEJvzBRgBIhMI7ZmM4KHHigMVWo7YBR0PdwFe'}}, {'toggleMenuServiceItemRenderer': {'defaultText': {'runs': [{'text': 'Subscribe'}]}, 'defaultIcon': {'iconType': 'SUBSCRIBE'}, 'defaultServiceEndpoint': {'clickTrackingParams': 'CH8QqJwGGAIiEwjtmYzgoceKAxVajtgFHQ93AV4=', 'subscribeEndpoint': {'channelIds': ['UCs61FMW9q9MIJXa154PbcYQ'], 'params': 'GAA%3D'}}, 'toggledText': {'runs': [{'text': 'Unsubscribe'}]}, 'toggledIcon': {'iconType': 'SUBSCRIBE'}, 'toggledServiceEndpoint': {'clickTrackingParams': 'CH8QqJwGGAIiEwjtmYzgoceKAxVajtgFHQ93AV4=', 'unsubscribeEndpoint': {'channelIds': ['UCs61FMW9q9MIJXa154PbcYQ'], 'params': 'GAA%3D'}}, 'trackingParams': 'CH8QqJwGGAIiEwjtmYzgoceKAxVajtgFHQ93AV4='}}, {'menuNavigationItemRenderer': {'text': {'runs': [{'text': 'Share'}]}, 'icon': {'iconType': 'SHARE'}, 'navigationEndpoint': {'clickTrackingParams': 'CH4QkfsFGAMiEwjtmYzgoceKAxVajtgFHQ93AV4=', 'shareEntityEndpoint': {'serializedShareEntity': 'GhhVQ3ZrN2w5aU9oNE5fVHdGMEtGT21iUXc%3D', 'sharePanelType': 'SHARE_PANEL_TYPE_UNIFIED_SHARE_PANEL'}}, 'trackingParams': 'CH4QkfsFGAMiEwjtmYzgoceKAxVajtgFHQ93AV4='}}], 'trackingParams': 'CH0QpzsiEwjtmYzgoceKAxVajtgFHQ93AV4=', 'accessibility': {'accessibilityData': {'label': 'Action menu'}}}}}
----------------
- {'runs': [{'text': 'Preston Reed', 'navigationEndpoint': {'clickTrackingParams': 'CHwQoLMCGAAiEwjtmYzgoceKAxVajtgFHQ93AV4=', 'browseEndpoint': {'browseId': 'UCvk7l9iOh4N_TwF0KFOmbQw', 'browseEndpointContextSupportedConfigs': {'browseEndpointContextMusicConfig': {'pageType': 'MUSIC_PAGE_TYPE_ARTIST'}}}}}]}
- [{'text': 'Preston Reed', 'navigationEndpoint': {'clickTrackingParams': 'CHwQoLMCGAAiEwjtmYzgoceKAxVajtgFHQ93AV4=', 'browseEndpoint': {'browseId': 'UCvk7l9iOh4N_TwF0KFOmbQw', 'browseEndpointContextSupportedConfigs': {'browseEndpointContextMusicConfig': {'pageType': 'MUSIC_PAGE_TYPE_ARTIST'}}}}}]
- {'text': 'Preston Reed', 'navigationEndpoint': {'clickTrackingParams': 'CHwQoLMCGAAiEwjtmYzgoceKAxVajtgFHQ93AV4=', 'browseEndpoint': {'browseId': 'UCvk7l9iOh4N_TwF0KFOmbQw', 'browseEndpointContextSupportedConfigs': {'browseEndpointContextMusicConfig': {'pageType': 'MUSIC_PAGE_TYPE_ARTIST'}}}}}
- {'clickTrackingParams': 'CHwQoLMCGAAiEwjtmYzgoceKAxVajtgFHQ93AV4=', 'browseEndpoint': {'browseId': 'UCvk7l9iOh4N_TwF0KFOmbQw', 'browseEndpointContextSupportedConfigs': {'browseEndpointContextMusicConfig': {'pageType': 'MUSIC_PAGE_TYPE_ARTIST'}}}}
- {'browseId': 'UCvk7l9iOh4N_TwF0KFOmbQw', 'browseEndpointContextSupportedConfigs': {'browseEndpointContextMusicConfig': {'pageType': 'MUSIC_PAGE_TYPE_ARTIST'}}}
- {'browseEndpointContextMusicConfig': {'pageType': 'MUSIC_PAGE_TYPE_ARTIST'}}
- {'pageType': 'MUSIC_PAGE_TYPE_ARTIST'}
- MUSIC_PAGE_TYPE_ARTIST
----------------
- {'runs': [{'text': '11.4K subscribers'}]}
- [{'text': '11.4K subscribers'}]
- {'text': '11.4K subscribers'}
- 11.4K subscribers
----------------
- {'runs': [{'text': 'Preston Reed', 'navigationEndpoint': {'clickTrackingParams': 'CHwQoLMCGAAiEwjtmYzgoceKAxVajtgFHQ93AV4=', 'browseEndpoint': {'browseId': 'UCvk7l9iOh4N_TwF0KFOmbQw', 'browseEndpointContextSupportedConfigs': {'browseEndpointContextMusicConfig': {'pageType': 'MUSIC_PAGE_TYPE_ARTIST'}}}}}]}
- [{'text': 'Preston Reed', 'navigationEndpoint': {'clickTrackingParams': 'CHwQoLMCGAAiEwjtmYzgoceKAxVajtgFHQ93AV4=', 'browseEndpoint': {'browseId': 'UCvk7l9iOh4N_TwF0KFOmbQw', 'browseEndpointContextSupportedConfigs': {'browseEndpointContextMusicConfig': {'pageType': 'MUSIC_PAGE_TYPE_ARTIST'}}}}}]
- {'text': 'Preston Reed', 'navigationEndpoint': {'clickTrackingParams': 'CHwQoLMCGAAiEwjtmYzgoceKAxVajtgFHQ93AV4=', 'browseEndpoint': {'browseId': 'UCvk7l9iOh4N_TwF0KFOmbQw', 'browseEndpointContextSupportedConfigs': {'browseEndpointContextMusicConfig': {'pageType': 'MUSIC_PAGE_TYPE_ARTIST'}}}}}
- Preston Reed
----------------
- {'runs': [{'text': 'Preston Reed', 'navigationEndpoint': {'clickTrackingParams': 'CHwQoLMCGAAiEwjtmYzgoceKAxVajtgFHQ93AV4=', 'browseEndpoint': {'browseId': 'UCvk7l9iOh4N_TwF0KFOmbQw', 'browseEndpointContextSupportedConfigs': {'browseEndpointContextMusicConfig': {'pageType': 'MUSIC_PAGE_TYPE_ARTIST'}}}}}]}
- [{'text': 'Preston Reed', 'navigationEndpoint': {'clickTrackingParams': 'CHwQoLMCGAAiEwjtmYzgoceKAxVajtgFHQ93AV4=', 'browseEndpoint': {'browseId': 'UCvk7l9iOh4N_TwF0KFOmbQw', 'browseEndpointContextSupportedConfigs': {'browseEndpointContextMusicConfig': {'pageType': 'MUSIC_PAGE_TYPE_ARTIST'}}}}}]
- {'text': 'Preston Reed', 'navigationEndpoint': {'clickTrackingParams': 'CHwQoLMCGAAiEwjtmYzgoceKAxVajtgFHQ93AV4=', 'browseEndpoint': {'browseId': 'UCvk7l9iOh4N_TwF0KFOmbQw', 'browseEndpointContextSupportedConfigs': {'browseEndpointContextMusicConfig': {'pageType': 'MUSIC_PAGE_TYPE_ARTIST'}}}}}
- {'clickTrackingParams': 'CHwQoLMCGAAiEwjtmYzgoceKAxVajtgFHQ93AV4=', 'browseEndpoint': {'browseId': 'UCvk7l9iOh4N_TwF0KFOmbQw', 'browseEndpointContextSupportedConfigs': {'browseEndpointContextMusicConfig': {'pageType': 'MUSIC_PAGE_TYPE_ARTIST'}}}}
- {'browseId': 'UCvk7l9iOh4N_TwF0KFOmbQw', 'browseEndpointContextSupportedConfigs': {'browseEndpointContextMusicConfig': {'pageType': 'MUSIC_PAGE_TYPE_ARTIST'}}}
- UCvk7l9iOh4N_TwF0KFOmbQw
----------------
- {'musicThumbnailRenderer': {'thumbnail': {'thumbnails': [{'url': 'https://lh3.googleusercontent.com/a-/ALV-UjUbQGzZ2_DL08yAi4pQAupcyj2upWfEkLSFajn7LbQ8dDngP9y4cQ=w226-h226-l90-rj', 'width': 226, 'height': 226}, {'url': 'https://lh3.googleusercontent.com/a-/ALV-UjUbQGzZ2_DL08yAi4pQAupcyj2upWfEkLSFajn7LbQ8dDngP9y4cQ=w544-h544-l90-rj', 'width': 544, 'height': 544}]}, 'thumbnailCrop': 'MUSIC_THUMBNAIL_CROP_CIRCLE', 'thumbnailScale': 'MUSIC_THUMBNAIL_SCALE_ASPECT_FILL', 'trackingParams': 'CIIBEIS_AiITCO2ZjOChx4oDFVqO2AUdD3cBXg=='}}
- {'thumbnail': {'thumbnails': [{'url': 'https://lh3.googleusercontent.com/a-/ALV-UjUbQGzZ2_DL08yAi4pQAupcyj2upWfEkLSFajn7LbQ8dDngP9y4cQ=w226-h226-l90-rj', 'width': 226, 'height': 226}, {'url': 'https://lh3.googleusercontent.com/a-/ALV-UjUbQGzZ2_DL08yAi4pQAupcyj2upWfEkLSFajn7LbQ8dDngP9y4cQ=w544-h544-l90-rj', 'width': 544, 'height': 544}]}, 'thumbnailCrop': 'MUSIC_THUMBNAIL_CROP_CIRCLE', 'thumbnailScale': 'MUSIC_THUMBNAIL_SCALE_ASPECT_FILL', 'trackingParams': 'CIIBEIS_AiITCO2ZjOChx4oDFVqO2AUdD3cBXg=='}
- {'thumbnails': [{'url': 'https://lh3.googleusercontent.com/a-/ALV-UjUbQGzZ2_DL08yAi4pQAupcyj2upWfEkLSFajn7LbQ8dDngP9y4cQ=w226-h226-l90-rj', 'width': 226, 'height': 226}, {'url': 'https://lh3.googleusercontent.com/a-/ALV-UjUbQGzZ2_DL08yAi4pQAupcyj2upWfEkLSFajn7LbQ8dDngP9y4cQ=w544-h544-l90-rj', 'width': 544, 'height': 544}]}
- [{'url': 'https://lh3.googleusercontent.com/a-/ALV-UjUbQGzZ2_DL08yAi4pQAupcyj2upWfEkLSFajn7LbQ8dDngP9y4cQ=w226-h226-l90-rj', 'width': 226, 'height': 226}, {'url': 'https://lh3.googleusercontent.com/a-/ALV-UjUbQGzZ2_DL08yAi4pQAupcyj2upWfEkLSFajn7LbQ8dDngP9y4cQ=w544-h544-l90-rj', 'width': 544, 'height': 544}]
```
The part right after the one above is where is starts with what looks like partial data, then fails:
```
- {'thumbnailRenderer': {'musicThumbnailRenderer': {'thumbnail': {'thumbnails': [{'url': 'https://i9.ytimg.com/vi_locker/8Xio21X5hLQ/locker.png?sqp=-oaymwEICOIBEOIBIAA&rs=AMzJL3m7hQC8IRXFqMaDJaLjVf4Cw77_iw', 'width': 226, 'height': 226}, {'url': 'https://i9.ytimg.com/vi_locker/8Xio21X5hLQ/locker.png?sqp=-oaymwEICKAEEKAEIAA&rs=AMzJL3kZS8e-k-iYR7QVCtQnQLuiGj3Vvg', 'width': 544, 'height': 544}]}, 'thumbnailCrop': 'MUSIC_THUMBNAIL_CROP_CIRCLE', 'thumbnailScale': 'MUSIC_THUMBNAIL_SCALE_ASPECT_FILL', 'trackingParams': 'CHsQhL8CIhMI7ZmM4KHHigMVWo7YBR0PdwFe'}}, 'aspectRatio': 'MUSIC_TWO_ROW_ITEM_THUMBNAIL_ASPECT_RATIO_SQUARE', 'title': {'runs': [{'text': 'Anthony M'}]}, 'subtitle': {}, 'navigationEndpoint': {'clickTrackingParams': 'CHoQoLMCGAEiEwjtmYzgoceKAxVajtgFHQ93AV4=', 'browseEndpoint': {'browseEndpointContextSupportedConfigs': {'browseEndpointContextMusicConfig': {'pageType': 'MUSIC_PAGE_TYPE_ARTIST'}}}}, 'trackingParams': 'CHoQoLMCGAEiEwjtmYzgoceKAxVajtgFHQ93AV4='}
----------------
- {'runs': [{'text': 'Anthony M'}]}
- [{'text': 'Anthony M'}]
- {'text': 'Anthony M'}
----------------
- {'clickTrackingParams': 'CHoQoLMCGAEiEwjtmYzgoceKAxVajtgFHQ93AV4=', 'browseEndpoint': {'browseEndpointContextSupportedConfigs': {'browseEndpointContextMusicConfig': {'pageType': 'MUSIC_PAGE_TYPE_ARTIST'}}}}
----------------
- {'runs': [{'text': 'Anthony M'}]}
- [{'text': 'Anthony M'}]
- {'text': 'Anthony M'}
- Anthony M
----------------
- {'clickTrackingParams': 'CHoQoLMCGAEiEwjtmYzgoceKAxVajtgFHQ93AV4=', 'browseEndpoint': {'browseEndpointContextSupportedConfigs': {'browseEndpointContextMusicConfig': {'pageType': 'MUSIC_PAGE_TYPE_ARTIST'}}}}
```
as you can see, it's missing a bunch of fields and eventually crashes, maybe because it's meeting a `'browseId'`

**Comment by sigma67** [comment]
Are you still facing this issue? If so, are you willing to submit a fix or provide reproduction instructions?

**Comment by Batwam** [comment]
I need to check if I'm using a patched version of ytmusicapi. I think that I did experience the issue again and had to go back and change the file manually again. 

The root cause is actually a bit of an edge case as YT Music seems to be recommending Albums from songs I created/uploaded but since deleted.
