### ISSUE TITLE
400 Bad Request error when using oauth, but browser authentication works

### ISSUE THREAD

**Issue by AntitrustEnthusiast** [sigma67/ytmusicapi#676]
**Describe the bug**
the `ytmusic.search()` command is throwing a `HTTP 400: Bad Request` error with the message `Request contains an invalid argument`, but only when using oauth. Browser authentication works fine. 

Using `ytmusicapi` version 1.8.2

**To Reproduce**
1. run `ytmusicapi oauth` as documented in setup
2. Minimal script example:
```python
from ytmusicapi import YTMusic

conn = YTMusic("oauth.json")
search_result = conn.search(f"It's beginning to look a lot like Christmas")
```

Result:
```
Traceback (most recent call last):
  File "C:\dev\ytmusic\test.py", line 4, in <module>
    search_result = conn.search(f"It's beginning to look a lot like Christmas")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\ytmusic\venv\Lib\site-packages\ytmusicapi\mixins\search.py", line 183, in search
    response = self._send_request(endpoint, body)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\ytmusic\venv\Lib\site-packages\ytmusicapi\ytmusic.py", line 241, in _send_request
    raise YTMusicServerError(message + error)
ytmusicapi.exceptions.YTMusicServerError: Server returned HTTP 400: Bad Request.
Request contains an invalid argument.
```

**Additional context**
I've been using it for quite a while without issue, but today it stopped working, seemingly at random. Switching to browser auth has temporarily fixed it for my workflow.

Deleting `oauth.json` and redoing the authentication flow didn't work either.

**Comment by zostay** [comment]
I too have started getting this, though, I can't get the browser auth to work either.

**Comment by sigma67** [comment]
Could you try messing with the headers to see if removing some fixes it? Hard to tell what the issue is without further indication

**Comment by AntitrustEnthusiast** [comment]
Hmm, I ran test requests using this code:
```python
from ytmusicapi import YTMusic
conn = YTMusic("oauth.json")
conn.rate_song("A4zBSnMhvI0", "LIKE")
```

While removing one of these headers each time:

* user-agent
* accept
* accept-encoding
* content-type
* content-encoding
* origin
* authorization
* X-Goog-Request-Time

All of them except `authorization` returned the exact same error message: `Request contains an invalid argument.`

Here's the full error from the API, in case it helps:

```json
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "errors": [
      {
        "message": "Request contains an invalid argument.",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
```

Also tried removing `?alt=json` from the endpoint, no change.

The only one that had a different result was removing the `authentication` header, which returned a `You must be signed in to perform this operation.` error.

**Comment by rafaeldrrmachado** [comment]
Does anyone know where the oauth.json file is stored? I can't findi it to try and delete it

**Comment by srajangarg** [comment]
same issue, commenting for visibility!

**Comment by AntitrustEnthusiast** [comment]
Someone in the linked spotify_to_ytmusic issue mentioned it works for them as Manager of their family plan, but not for their wife and kids (non-managers).

I am in the same situation, is everyone else experiencing the issue also a non-manager on a family plan?

**Comment by hhh4hn** [comment]
> everyone else experiencing the issue also a non-manager on a family plan?

This seems related to what I've noticed: it's working fine for me when using oauth creds for one account that is a primary account of mine, but it does not work on another which is a "brand account" under a second account. I get `400: Bad Request` on any call using that brand account.

**Comment by apastel** [comment]
> everyone else experiencing the issue also a non-manager on a family plan?

My account **is** the manager of my family plan and I get the `400: Bad Request` error when using oauth creds.

**Comment by sabad67** [comment]
i am seeing this issue as a manager of a family plan.

**Comment by soreikomori** [comment]
Same here when calling yt.get_history(). I also tried updating to no avail. Currently on ver. 1.8.2.

**Comment by secnonsense** [comment]
I have an individual plan and am also seeing this error.  Maybe the issue is due to having multiple accounts on the plan?  In my instance I use a branded account instead of my primary gmail.com account.  I saw the error using my branded account, however after regenerating my oauth.json using my gmail.com account everything worked as expected.

**Comment by Batwam** [comment]
I'm also getting this HTTP 400 error for the last few days. Glad to see I'm not alone. I tried to generate oauth.json from 2 separate accounts and both of them fail.

**Comment by parthcooks** [comment]
it was working for me till yesterday , today even im facing this issue , sigma67 is there any fix for this?

**Comment by abetwothree** [comment]
Seeing same issue. Tried multiple accounts and it all fails locally and on a server. However, it does work locally without an oauth.json file.

**Comment by apastel** [comment]
People in different projects are saying that Google is removing OAuth support for YTMusic, and they are switching back to using cookies :cry:  The reason it happens for some accounts and not others of course is because of A/B testing.

https://github.com/KoljaWindeler/ytube_music_player/issues/367#issuecomment-2472397147
https://github.com/music-assistant/hass-music-assistant/issues/3138#issuecomment-2471316657
https://github.com/yt-dlp/yt-dlp/issues/11462#issuecomment-2471087887

I haven't seen anything conclusive stating this to be true, but it seems like developers of different projects are seeing the writing on the wall, which points toward bye-bye for OAuth. Let's hope that's not the case...I'm not sure how to determine if it is or not.

**Comment by jurgenweber** [comment]
> The reason it happens for some accounts and not others of course is because of A/B testing.

I agree, either A/B Testing or the nature of the global rollout.

removing OAuth just seems like a direct stab at disabling these sorts of integrations.

**Comment by sigma67** [comment]
As expected this is a widespread issue affecting all third-party oauth clients: https://github.com/yt-dlp/yt-dlp/issues/11462

Is anyone facing issues with browser-based auth also? Seems to be working ok for me

**Comment by srajangarg** [comment]
> As expected this is a widespread issue affecting all third-party oauth clients: [yt-dlp/yt-dlp#11462](https://github.com/yt-dlp/yt-dlp/issues/11462)
> 
> Is anyone facing issues with browser-based auth also? Seems to be working ok for me

@sigma67 confirming that browser-based auth also works for me

**Comment by luisignaciocc** [comment]
For me, browser-based authentication doesn't work either. Using the get_history()

**Comment by ohadklein11** [comment]
Referencing my workaround solution from the spotify2ytmusic tool:
https://github.com/linsomniac/spotify_to_ytmusic/issues/125#issuecomment-2481207542
Hope this helps you all.

**Comment by Big-Shark** [comment]
Browser works for me, but only when i changed browseId to FEmusic_explore

**Comment by Batwam** [comment]
same here, works with browser authentications, the instructions are here: https://ytmusicapi.readthedocs.io/en/stable/setup/browser.html

**Comment by sigma67** [comment]
Common advice to make long-lasting cookies is to create them using the browser's in-private session. This avoids accidentally messing with the session during your regular browsing activity

The cookies last quite long in my experience

**Comment by Batwam** [comment]
that's good to know, thanks

**Comment by Hengen42** [comment]
I couldn't manage to get cookies in the brave browser. I keep getting a 401 error.

**Comment by Hengen42** [comment]
"te": "trailers\u001a"

I solved the issue by removing this code from the browser.json file. However, I've been struggling with it for hours. It was so silly.
Example: (where there was a space there was the usual "te": "trailers\u001a".)

```
{
    "accept": "",
    "accept-encoding": "",
    "accept-language": "",
    "authorization": "",
    "connection": "",
    "content-encoding": "",
    "content-type": "",
    "cookie": "",
    "origin": "",
    "priority": "",
    "referer": "",

    "user-agent": "",
    "x-goog-authuser": "",
    "x-goog-visitor-id": "",
    "x-kl-ajax-request": "",
    "x-origin": "",
    "x-youtube-bootstrap-logged-in": "",
    "x-youtube-client-name": "",
    "x-youtube-client-version": ""
}
```
