### ISSUE TITLE
OAuth client does not refresh the token

### ISSUE THREAD

**Issue by inoricat** [sigma67/ytmusicapi#705]
**Describe the bug**
Upon using the oauth token json generated by `ytmusicapi oauth`, it expires in around an hour, and is not refreshed on the next needed call.

**To Reproduce**
*ytmusicapi version 1.9.1*
1. Get a fresh token with `ytmusicapi oauth`
2. Use the library to check that it works
3. Come back in an hour (or do a long running operation of queries) and do another query
4. Next call will raise an exception.

**Additional context**
Had my code running with debug so I caught some extra context, it seems it tries to refresh but the network call returns 401
```
2024-12-28 15:53:26,166 DEBUG 1049:connectionpool.py(21976) - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2024-12-28 15:53:26,292 DEBUG 544:connectionpool.py(21976) - https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 401 None
Traceback (most recent call last):
  File "C:\Coding\python\spaghetti-exporter\main.py", line 97, in <module>
    pl_gen = [f"{s['track']['artists'][0]['name']} - {s['track']['name']}" for s in sp_pl]
                  ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Coding\python\spaghetti-exporter\.venv\Lib\site-packages\ytmusicapi\mixins\search.py", line 183, in search
    response = self._send_request(endpoint, body)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Coding\python\spaghetti-exporter\.venv\Lib\site-packages\ytmusicapi\ytmusic.py", line 270, in _send_request
    headers=self.headers,
            ^^^^^^^^^^^^
  File "C:\Coding\python\spaghetti-exporter\.venv\Lib\site-packages\ytmusicapi\ytmusic.py", line 221, in headers
    self._headers["authorization"] = self._token.as_auth()
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Coding\python\spaghetti-exporter\.venv\Lib\site-packages\ytmusicapi\auth\oauth\token.py", line 43, in as_auth
    return f"{self.token_type} {self.access_token}"
                                ^^^^^^^^^^^^^^^^^
  File "C:\Coding\python\spaghetti-exporter\.venv\Lib\site-packages\ytmusicapi\auth\oauth\token.py", line 96, in __getattribute__
    fresh = self.credentials.refresh_token(self.refresh_token)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Coding\python\spaghetti-exporter\.venv\Lib\site-packages\ytmusicapi\auth\oauth\credentials.py", line 121, in refresh_token
    response = self._send_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Coding\python\spaghetti-exporter\.venv\Lib\site-packages\ytmusicapi\auth\oauth\credentials.py", line 91, in _send_request
    raise BadOAuthClient(
ytmusicapi.auth.oauth.exceptions.BadOAuthClient: OAuth client failure. Most likely client_id and client_secret mismatch or YouTubeData API is not enabled.
```

**Comment by inoricat** [comment]
Nevermind, turns out I was passing an incorrect client_secret... It works correctly now. My apologies
