### ISSUE TITLE
get_library_upload_songs() throws KeyError if there are no uploaded songs

### ISSUE THREAD

**Issue by apastel** [sigma67/ytmusicapi#71]
`get_library_upload_albums()` returns an empty list when there are no uploaded albums.

But `get_library_upload_songs()` and `get_library_upload_artists()` both throw a KeyError if either of them are empty.

I propose that they also return an empty list for consistency and ease of error handling.

```
>>> from ytmusicapi import YTMusic
>>> youtube_auth = YTMusic('headers_auth.json')
>>> youtube_auth.get_library_upload_albums()
[]
>>> youtube_auth.get_library_upload_songs()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/apastel/dev/ytmusic-deleter/venv/lib/python3.6/site-packages/ytmusicapi/mixins/uploads.py", line 36, in get_library_upload_songs
    results = nav(results, ITEM_SECTION)['musicShelfRenderer']
KeyError: 'musicShelfRenderer'
>>> youtube_auth.get_library_upload_artists()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/apastel/dev/ytmusic-deleter/venv/lib/python3.6/site-packages/ytmusicapi/mixins/uploads.py", line 93, in get_library_upload_artists
    results = nav(results, ITEM_SECTION)['musicShelfRenderer']
KeyError: 'musicShelfRenderer'
```

**Comment by sigma67** [comment]
Good point, do you want to tackle this?

**Comment by apastel** [comment]
I might be able to, yes.
